config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'about-us',to: 'about#index', as: :about
  # get '/',to: 'main#index'
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  root to: "main#index" 
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: {with: /\A[^@\s]+@[^\s]+\z/, message: "must be a valid email address."}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController<ApplicationController
    def index
        flash[:notice]="Logged in successfully"
        flash[:alert]="Invalid credentials"
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
        
    end
    def create
        @user = User.find_by(email: params[:email])
        # send mail
        if @user.present?
            # send eamil
            PasswordMailer.with(user: @user).reset.deliver_now

        end
        redirect_to root_path, notice: "If an account with that email was found, we have sent the link to reset your password"
         
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset") #if you cant verify that token User.find_signed! method throws an exception
    rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please try again"    
        # binding.irb #used to inspect that user is exists or not but because of token is expired the user is nil.    
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was reset successfully. please sign in"
        else
            render :edit
            
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
        
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit
        
    end
    def update
        if Current.user.update(password_params)
            redirect_to(root_path, notice: "Password updated")

        else  
            render :edit
        end
    end
    private

    def password_params
        params.require(:user).permit(:password,:password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        # render plain: "Thanks!"
        # params ==>  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"avdhu", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
        # render plain: params[:user]
        # {"email"=>"avdhu", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign Up"}
        # @user = User.new(params[:user])
        @user = User.new(user_params)
        puts "parw23456543456434543234543 #{user_params}"
        if @user.save
            redirect_to_root_path, flash[:notice]= "Successfully created account"
        else
            flash[:alert] = "Something was wrong"
            render :new
            
        end
    end
    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
        # params[:user]        
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    
    def new
        
    end
    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged In successfully"
        else
            flash[:alert] = "Invalid Email or password"
            render :new
        end
    end
    
    
    
    def destroy
        session[:user_id]=nil
        redirect_to root_path, notice: "Logged out successfully"

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="container">
    <h1>About page<h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gorails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar"%>
  <div class="container">
  <%= render partial: "shared/flash"%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center my-4">
    <h1>Welcome to Home <h1>
</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message|%>
                <div><%= message%></div>
            <% end %>                           
        </div>
    <% end %>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "enter password" %>
    </div>
    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "enter confirm password"%>
    </div>
   
     <div class="mb-3">
        <%= form.submit "Password Reset", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with url: password_reset_path do |form| %>
     <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" , placeholder: "enter email" %>
    </div>
   
     <div class="mb-3">
        <%= form.submit "Password Reset", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/session/new.html.erb
<h1>Sign In</h1>

<%= form_with url: sign_in_path do |form| %>

 
      <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" , placeholder: "enter email" %>
    </div>
    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "enter password" %>
        <%= link_to "Forgot Your password?", password_reset_path %>

    </div>

     <div class="mb-3">
        <%= form.submit "Sign In", class: "btn btn-primary" %>
    </div>
<% end %> 

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice]%>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert]%>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%= link_to "Home", root_path, class:"nav-link" %>
        <%# <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a> %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class:"nav-link"%>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>